name: pictool
version: git
summary: command line program for manipulating and altering images
description: |
  pictool is a command line program for manipulating and altering images.
base: core20
confinement: strict

parts:
  pictool:
    plugin: python
    source: .
    build-packages:
      - pkg-config
      - libcairo2-dev
      - libpython3.8-dev
      - python3.8-dev
      - libgirepository1.0-dev
    stage-packages:
      - gir1.2-gexiv2-0.10
      - gir1.2-glib-2.0

apps:
  pictool:
    command: bin/pictool
    plugs:
      - network
      - home
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.8/site-packages/
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
