name: pictool

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install tox
      run: |
        sudo apt install --yes libgirepository1.0-dev libcairo2-dev pkg-config
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint with flake8
      run: |
        tox -epep8
  build-and-run-snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
    - run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        pictool -h
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: |
        sudo apt install --yes libgirepository1.0-dev libcairo2-dev pkg-config gir1.2-gexiv2-0.10 gir1.2-gexiv2-0.10
        python -m pip install --upgrade pip
        pip install tox
    - name: tox
      run: |
        tox -e${{ matrix.python-version }}
